version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: db_ignite
    # Comando que reinicia automaticamente o container se ele parar
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
    # Criamos esta propriedade para que o Banco de Dados e a Aplicação rodem no mesmo local
    network_mode: bridge

  app:
    build: .
    container_name: rentalx
    ports: 
     - 3333:3333
    volumes:
      - .:/user/app
    # Criamos esta propriedade para que o Banco de Dados e a Aplicação rodem no mesmo local
    network_mode: bridge

volumes:
  pgdata:
    driver: local