version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: db_ignite
    # Comando que reinicia automaticamente o container se ele parar
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentalx
    # Comando que reinicia automaticamente o container se ele parar
    restart: always
    ports: 
     - 3333:3333
    volumes:
      - .:/user/app
    links:
      - database_ignite
    depends_on:
      - database_ignite

volumes:
  pgdata:
    driver: local